server:
  port: 9090

spring:
  datasource:
    name: test
    url: jdbc:mysql://192.168.31.163:3306/blog?useUnicode=true&characterEncoding=utf8&serverTimezone=UTC&useSSL=false
    username: root
    password: root
    driver-class-name: com.mysql.jdbc.Driver
    filters: stat
    maxActive: 20
    initialSize: 1
    maxWait: 60000
    minIdle: 1
    timeBetweenEvictionRunsMillis: 60000
    minEvictableIdleTimeMillis: 300000
    validationQuery: select 'x'
    testWhileIdle: true
    testOnBorrow: false
    testOnReturn: false
    poolPreparedStatements: true
    maxOpenPreparedStatements: 20

# mybatis-plus配置
mybatis-plus:
  mapper-locations: classpath:mapper/**/*Mapper.xml
  type-aliases-package: com.stupidwind.blog.domain.entity
  global-config:
    db-config:
      db-type: mysql
      logic-delete-value: 0
      logic-not-delete-value: 1
  configuration:
    cache-enabled: false
    jdbc-type-for-null: null
